<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="3" ignored="0" total="8" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="44226" started-at="2019-03-14T07:33:41Z" finished-at="2019-03-14T07:34:25Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="44226" started-at="2019-03-14T07:33:41Z" finished-at="2019-03-14T07:34:25Z">
      <class name="com.ecshop.tests.LoginTest">
        <test-method status="PASS" signature="initDriver()[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="initDriver" is-config="true" duration-ms="4421" started-at="2019-03-14T15:33:42Z" finished-at="2019-03-14T15:33:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method status="PASS" signature="LoginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="LoginTest" duration-ms="3048" started-at="2019-03-14T15:33:46Z" data-provider="loginData" finished-at="2019-03-14T15:33:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ding]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[登录成功]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="quitDriver" is-config="true" duration-ms="200" started-at="2019-03-14T15:33:49Z" finished-at="2019-03-14T15:33:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method status="PASS" signature="initDriver()[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="initDriver" is-config="true" duration-ms="2793" started-at="2019-03-14T15:33:49Z" finished-at="2019-03-14T15:33:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method status="PASS" signature="LoginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="LoginTest" duration-ms="2217" started-at="2019-03-14T15:33:52Z" data-provider="loginData" finished-at="2019-03-14T15:33:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ding]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[777777]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[用户名或密码错误]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="quitDriver" is-config="true" duration-ms="193" started-at="2019-03-14T15:33:54Z" finished-at="2019-03-14T15:33:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method status="PASS" signature="initDriver()[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="initDriver" is-config="true" duration-ms="2770" started-at="2019-03-14T15:33:54Z" finished-at="2019-03-14T15:33:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method status="PASS" signature="LoginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="LoginTest" duration-ms="2193" started-at="2019-03-14T15:33:57Z" data-provider="loginData" finished-at="2019-03-14T15:33:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ding123]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[用户名或密码错误]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="quitDriver" is-config="true" duration-ms="318" started-at="2019-03-14T15:33:59Z" finished-at="2019-03-14T15:34:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method status="PASS" signature="initDriver()[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="initDriver" is-config="true" duration-ms="2621" started-at="2019-03-14T15:34:00Z" finished-at="2019-03-14T15:34:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method status="SKIP" signature="LoginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="LoginTest" duration-ms="2091" started-at="2019-03-14T15:34:02Z" data-provider="loginData" finished-at="2019-03-14T15:34:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[用户名不能为空]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.ecshop.pages.UserPage.assert_alert_text(UserPage.java:69)
	at com.ecshop.tests.LoginTest.LoginTest(LoginTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="quitDriver" is-config="true" duration-ms="347" started-at="2019-03-14T15:34:04Z" finished-at="2019-03-14T15:34:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method status="PASS" signature="initDriver()[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="initDriver" is-config="true" duration-ms="2735" started-at="2019-03-14T15:34:05Z" finished-at="2019-03-14T15:34:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method status="SKIP" signature="LoginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="LoginTest" duration-ms="2051" started-at="2019-03-14T15:34:08Z" data-provider="loginData" finished-at="2019-03-14T15:34:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[用户名不能为空]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.ecshop.pages.UserPage.assert_alert_text(UserPage.java:69)
	at com.ecshop.tests.LoginTest.LoginTest(LoginTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="quitDriver" is-config="true" duration-ms="329" started-at="2019-03-14T15:34:10Z" finished-at="2019-03-14T15:34:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method status="PASS" signature="initDriver()[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="initDriver" is-config="true" duration-ms="2679" started-at="2019-03-14T15:34:10Z" finished-at="2019-03-14T15:34:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method status="FAIL" signature="LoginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="LoginTest" duration-ms="2043" started-at="2019-03-14T15:34:13Z" data-provider="loginData" finished-at="2019-03-14T15:34:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[用户名不能为空]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.ecshop.pages.UserPage.assert_alert_text(UserPage.java:69)
	at com.ecshop.tests.LoginTest.LoginTest(LoginTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="quitDriver" is-config="true" duration-ms="347" started-at="2019-03-14T15:34:15Z" finished-at="2019-03-14T15:34:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method status="PASS" signature="initDriver()[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="initDriver" is-config="true" duration-ms="2657" started-at="2019-03-14T15:34:15Z" finished-at="2019-03-14T15:34:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method status="FAIL" signature="LoginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="LoginTest" duration-ms="2094" started-at="2019-03-14T15:34:18Z" data-provider="loginData" finished-at="2019-03-14T15:34:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ding]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[登录密码不能为空]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.ecshop.pages.UserPage.assert_alert_text(UserPage.java:69)
	at com.ecshop.tests.LoginTest.LoginTest(LoginTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="quitDriver" is-config="true" duration-ms="218" started-at="2019-03-14T15:34:20Z" finished-at="2019-03-14T15:34:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method status="PASS" signature="initDriver()[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="initDriver" is-config="true" duration-ms="2740" started-at="2019-03-14T15:34:20Z" finished-at="2019-03-14T15:34:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method status="FAIL" signature="LoginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="LoginTest" duration-ms="2034" started-at="2019-03-14T15:34:23Z" data-provider="loginData" finished-at="2019-03-14T15:34:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ding]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[登录密码不能为空]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.ecshop.pages.UserPage.assert_alert_text(UserPage.java:69)
	at com.ecshop.tests.LoginTest.LoginTest(LoginTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="quitDriver" is-config="true" duration-ms="351" started-at="2019-03-14T15:34:25Z" finished-at="2019-03-14T15:34:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method status="PASS" signature="closeService()[pri:0, instance:com.ecshop.tests.LoginTest@14bf9759]" name="closeService" is-config="true" duration-ms="736" started-at="2019-03-14T15:34:25Z" finished-at="2019-03-14T15:34:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeService -->
      </class> <!-- com.ecshop.tests.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
